# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:

  errors:
    avoid_print: error
    prefer_single_quotes: error
    require_trailing_commas: error
    avoid_unnecessary_containers: error
    curly_braces_in_flow_control_structures: error
    deprecated_consistency: error
    null_check_on_nullable_type_parameter: error
    prefer_const_declarations: error
    prefer_is_empty: error
    sort_child_properties_last: error
    unawaited_futures: error
    unnecessary_new: error
    library_prefixes: error
    always_declare_return_types: error
    await_only_futures: error
    comment_references: error
#    non_constant_identifier_names: error
#    file_names: error
#    package_names: error
#    use_build_context_synchronously: error


linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    avoid_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    require_trailing_commas: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
