class Autogenerated {
  List<FieldSetsModel>? fieldSets;

  Autogenerated({this.fieldSets});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['fieldSets'] != null) {
      fieldSets = <FieldSetsModel>[];
      json['fieldSets'].forEach((v) {
        fieldSets!.add(new FieldSetsModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.fieldSets != null) {
      data['fieldSets'] = this.fieldSets!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class FieldSetsModel {
  String? fieldSetId;
  String? fieldSetName;
  List<RecipientFieldsModel>? fields;

  FieldSetsModel({this.fieldSetId, this.fieldSetName, this.fields});

  FieldSetsModel.fromJson(Map<String, dynamic> json) {
    fieldSetId = json['fieldSetId'];
    fieldSetName = json['fieldSetName'];
    if (json['fields'] != null) {
      fields = <RecipientFieldsModel>[];
      json['fields'].forEach((v) {
        fields!.add(new RecipientFieldsModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['fieldSetId'] = this.fieldSetId;
    data['fieldSetName'] = this.fieldSetName;
    if (this.fields != null) {
      data['fields'] = this.fields!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class RecipientFieldsModel {
  String? fieldType;
  int? minLength;
  int? maxLength;
  String? fieldId;
  String? name;
  String? hintText;
  bool? isRequired;
  String? placeholderText;
  String? regex;
  String? value;
  List<Options>? options;

  RecipientFieldsModel(
      {this.fieldType,
        this.minLength,
        this.maxLength,
        this.fieldId,
        this.name,
        this.hintText,
        this.isRequired,
        this.placeholderText,
        this.regex,
        this.value,
        this.options});

  RecipientFieldsModel.fromJson(Map<String, dynamic> json) {
    fieldType = json['fieldType'];
    minLength = json['minLength'];
    maxLength = json['maxLength'];
    fieldId = json['fieldId'];
    name = json['name'];
    hintText = json['hintText'];
    isRequired = json['isRequired'];
    placeholderText = json['placeholderText'];
    regex = json['regex'];
    if (json['options'] != null) {
      options = <Options>[];
      json['options'].forEach((v) {
        options!.add(new Options.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['fieldType'] = this.fieldType;
    data['minLength'] = this.minLength;
    data['maxLength'] = this.maxLength;
    data['fieldId'] = this.fieldId;
    data['name'] = this.name;
    data['hintText'] = this.hintText;
    data['isRequired'] = this.isRequired;
    data['placeholderText'] = this.placeholderText;
    data['regex'] = this.regex;
    if (this.options != null) {
      data['options'] = this.options!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Options {
  String? id;
  String? name;

  Options({this.id, this.name});

  Options.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
}

class AddRecipientFieldModel {
  String? id;
  String? type;
  String? value;

  AddRecipientFieldModel({this.id, this.type,this.value});

  AddRecipientFieldModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    type = json['type'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['type'] = this.type;
    data['value'] = this.value;
    return data;
  }
}

class PhoneNumberModel {
  String? countryIso3Code;
  int? countryPhoneCode;
  String? number;

  PhoneNumberModel({this.countryIso3Code, this.countryPhoneCode,this.number});

}